In [14]:
'''
Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random 
and find out the mean of the elements using basic numpy functions.
'''
import numpy as np
arr = np.random.random((10, 1))
m=np.mean(arr)
print("The array is:\n{}\nMean={}".format(arr,m))

The array is:
[[0.79421068]
 [0.38375796]
 [0.96666144]
 [0.70378672]
 [0.88014599]
 [0.33882417]
 [0.70832634]
 [0.26484973]
 [0.27953157]
 [0.56128949]]
Mean=0.588138408606252


In [7]:
'''
Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random 
find the variance and standard deviation of the elements.
'''
import numpy as np
arr = np.random.random((20, 1))
sd=np.std(arr)
var=sd**2
print("The array is:\n{}\nVariance={}\nStandard Deviation={}".format(arr,var,sd))


The array is:
[[0.68290706]
 [0.21227294]
 [0.65043596]
 [0.85576639]
 [0.76383375]
 [0.20506891]
 [0.78707489]
 [0.3344238 ]
 [0.86062202]
 [0.91636408]
 [0.78370597]
 [0.80039522]
 [0.45536111]
 [0.49794318]
 [0.99048155]
 [0.1767959 ]
 [0.09794824]
 [0.18740618]
 [0.3223373 ]
 [0.29962879]]
Variance=0.08226556378059383
Standard Deviation=0.2868197409185669


In [15]:
'''
Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. 
Print the matrix which is the matrix multiplication of A and B. 
The shape of the new matrix should be (10,25). 
Using basic numpy math functions only find the sum of all the elements of the new matrix.
'''
import numpy as np
A = np.random.random((10,20))
print("Matrix A is: \n",A,"\n")
B = np.random.random((20,25))
print("Matrix B is: \n",B,"\n")
C=np.matmul(A, B)
print("Multiplication of a and B: \n",C,"\n")
print("Sum of elements of C:",np.sum(C))

Matrix A is: 
 [[0.77696301 0.99410028 0.77994146 0.28430373 0.46280208 0.23778763
  0.14168726 0.42436556 0.60785902 0.26495201 0.17747668 0.63967995
  0.24011872 0.27757968 0.48151977 0.97180182 0.77985975 0.73897254
  0.13228461 0.19303444]
 [0.17386858 0.17311446 0.242541   0.71377835 0.10577563 0.25119486
  0.84711561 0.66412099 0.17402722 0.22999418 0.28678023 0.47602948
  0.92498763 0.59659487 0.49108679 0.79629961 0.0215829  0.92679771
  0.982494   0.47464865]
 [0.32502651 0.18403182 0.25215597 0.25772878 0.84492765 0.69125354
  0.84683718 0.53161501 0.62442263 0.98604897 0.87559455 0.42134417
  0.30390255 0.09789655 0.48865587 0.79625716 0.3186865  0.47708058
  0.60200511 0.3137654 ]
 [0.70694129 0.78468165 0.09065716 0.93941955 0.02863512 0.81238693
  0.67048965 0.04435806 0.98793908 0.65530657 0.02790279 0.47843831
  0.63818476 0.29379836 0.85846677 0.42379161 0.62131176 0.98186681
  0.22221458 0.82060196]
 [0.78635699 0.64205205 0.51776102 0.6046555  0.18917893 0.96951248
 

Multiplication of a and B: 
 [[3.71199068 4.20109473 4.41658724 5.34887908 4.99239801 3.68124605
  4.96661652 4.72680013 5.21990387 6.37981283 4.23769731 5.21949668
  3.53625328 5.35368273 4.34039235 3.50720255 3.6945379  6.21049405
  5.68699944 4.93812143 4.75656944 4.98583504 4.9500079  4.2485909
  3.6407817 ]
 [4.95110133 3.73813991 3.88666561 5.48777117 5.48033702 3.0505017
  4.12383831 4.21044823 5.71481338 5.80909219 4.28460898 5.38384551
  4.2279048  6.33629774 4.80800508 3.4963526  4.33714072 5.42515141
  5.66801994 4.10154459 4.91323174 4.81502714 5.51221575 4.0595985
  4.89590968]
 [4.22959556 4.40289824 4.35524831 5.46275776 5.04527357 3.0237502
  4.92853695 4.65636929 6.1070552  6.26629157 4.13396406 5.80280739
  4.1798107  6.68117943 4.37149528 3.61354606 4.80520084 6.75307802
  6.27081988 5.0029703  4.66824974 5.08557305 5.06150203 4.71079602
  4.82357106]
 [5.10911141 4.38855574 4.6812385  5.86430047 5.71708055 2.97651086
  5.3798181  5.56083053 7.19727485 7.39408606 5.1

In [21]:
'''
Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) 
such that each element is the following function applied on each element of A. 

f(x)=1 / (1 + exp(-x)) 
Apply this function to each element of A and print the new array holding the value the function returns
Example:

a=[a1,a2,a3]   
n(new array to be printed )=[ f(a1), f(a2), f(a3)]

'''

import numpy as np
A = np.random.random((10,1))

print("The original matrix is:\n{}\n".format(A))

def funct(num):
    return (1 / (1 + np.exp(-num)))

n = np.apply_along_axis(funct, 0, A)
print("The result matrix is:\n{}\n".format(n))

The original matrix is:
[[0.0382249 ]
 [0.42896491]
 [0.68689466]
 [0.35993959]
 [0.01426541]
 [0.38829062]
 [0.61608602]
 [0.35346903]
 [0.93800644]
 [0.34789874]]

The result matrix is:
[[0.50955506]
 [0.60562647]
 [0.66527577]
 [0.58902581]
 [0.50356629]
 [0.59587113]
 [0.64932785]
 [0.58745856]
 [0.71869679]
 [0.58610794]]

